name: Building Images

on:
  push:
    branches:
      - main

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/zypher-game/zytron-op-geth
        tags: |
          type=raw,value=latest  
          type=raw,value={{branch}}-{{sha}}-{{date 'x'}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
